dist: xenial
sudo: required
language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: deploy
    python: 3.7
    install: skip
    script: skip
    if: NOT type = pull_request
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: romesh
      password:
        secure: AerhY1OHw3hOOJ+GoCiV4t0eF7Gwi4saiGiwxlkLFadiCbc+jOr6Ncq3KwvDTLqbWxP4AAwejVM3LlRb6sBoyAueY6rwHDBBMRph8R0SwtnW+iTB90EQLxsvs5K+Hl7+x8rk5tYXI3qt4nnyraXmJMGtCk/EX8bViXJ3oixZj8YT/Vg3LD/WOhqiC7YGhs5KEJKXy8nKdtPJzwdkV1QlxJqB67BB8mw+zBZHI24zSrXE8QD2D1MIJFtM9WeexA9Cgw7tfI9eyo7I0FBpb9bACEMZl7gvUGJZUHLH8gg+yY7jY+0cK6Izn37yqHEWq57ajGHfkDObGnRgrbEj6pWrWTJND9cyoqHZ7xlY53CUGr359UFkx60MF2TmdxiQsxH2Xgufd9colTzgnNdMvQZUQeFwLSiegqA7EhQ6yHYeBJKk5mecPZZ2NQAe3IZhdkeMi0bB9602CIXjZfb1kvYO9YrwMbztVNECEhOyKeYXoZdbUi6TF0LMT/hGm4QbtSzh3r6wbFocXIQK1mVokn5gsGARqRAbUYnL50c7+eTHKPkuuJDduVBcUvePLDWvfSN6JqxziaLsRpvNqTzQqr+n+G9vZssIDWkE/guEJyCNsiTryelS93PW9+ESrHg/PzW2eGZpMW+FvnFWnkii2kGzrB9cEluV1JndndVV2ZAWL3o=
