dist: xenial
sudo: required
language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: deploy
    python: 3.7
    install: skip
    script: skip
    if: NOT type = pull_request
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: romesh
    on:
      repo: atomicateam/atomica
dd:
  secure: fpt3SP0/JpesEkWrFwMNy0zBzkKE/Hkpl5k4IVVstJoKPxadGx2+gdDICi8F4nTiajgNlHysY48XUXGOG383HG1GbJE4IyDYHOB3e5TdLPuErHpe6Kd/tbYnBsFHd8Ab513z0lhBjmnm/TyX3YD7+bzqBvU3aIDR3S9ir4RQQyo1iR5UvmwWLKeIqveGPdzyZMMzGNeD6yAeD1nFr91P03tw6aVNunAB6lesdkWZJ8aHFIS3CodCeUp19UFoNIwQReRIHjrgvofKosjRJW67tVqfAuLU8wVhcPlwb+AiZipYhNhEjl8OgZxZD9nKP6YMVX52wi23djUKTojoJqBifj4p/ew9/Y14r7lwSUjkK/0wftofVdL8cffejSUY5XmwnRYCV55wW70I9KhuhYDAFNUS59LAgvAuwsh2v7KstLASXBERVh4iW/qzntsE47TCYv/tiM124pkw+tPdy97rJfP0n7yU/jrLIhpZED7ZpZBqxhSc7F8+um4uC43wnuqCmrBh1Llm3bqlQFn6qZZdhBmS9CQcs1d3DsgxCbebtoy2+j7JOe3/Km0y4r2NkF6rSbAmh/Em/K7EJ1h2qKRcrGEH1sCii1IIoSlTA9wSMWFOZ0Gx11A+BwLRByGeruCfe7kxoHDXjgqS+CS4W1bwqUMUfqZlmY3oPHwZXr55r0A=
