dist: xenial
sudo: required
language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: deploy
    python: 3.7
    install: skip
    script: skip
    if: NOT type = pull_request
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: romesh
      password:
        secure: G3aGJFwXt8fjK9EGmMROkDnkoRXKz6KP/EbkcUmlaAyY7bD8w+eZhvRXCJcPrEvIGcYXB3kSmfzobSv8JYLsaEA+EJ9YvvFfRi+e2R/HAKTQN0MdpfneS0vWY6qHLmpAf+IONDjZUCLW99/kqtV6i3z7wG9oaPvIzeUSH1r/iZbAyoCP9vwajMfqbUVgfrAwJke2njVCO0Ry8gjubY+cFxBUQOy/+HXazU5f5sqL8S7vdJubcQ+ieFKfu4TxVyI1kJtKK0+qb8OxW//1cw4j/NPhz0WN82Gk41r6RmqZjclybXm0WW8jCrZl/k33MJUcc2ypyweSdXzmMvHcLzXpfkEHQ/URZVjUMhDXwPOsq6pO9P+rFMzodsV1ZiaDhS2aXGaNHcABEggsK4ZjHyCPDt/UL90+k+RejL2+3kEzVOpXhvCaz0gWwCskKhcVy8cfWRGJfO4bBKUVkMtXzHXgYzm/dfqYemQiQOmjm4zzm7prC79oesSeWRTT5BnrL6KbpAKocUbYMQ9R4QHJgCg8WYCPYqLmLrOiquyfPzhpM4L5EDsfqfG4S+CStMenoVb2euY0pu1H3329277b+eqLf/CEaJcI+y5kp/ujFoMrsG9L3CJhcWz1ls/kzIhJ2UIaDmL5i+hbC832pVRIo6/1TGFQzuUm4JogdeF28yRjglk=
