dist: xenial
sudo: required
language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: deploy
    python: 3.7
    install: skip
    script: skip
    if: NOT type = pull_request
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: romesh
      password:
        secure: M4Tc+92hSui0nsZ4U6YqXFomvOiUrl++0iqzwlxN74xsMzHxos4KlpBbhvTQDde8+xC4776WD989jKscrnodpT3W+VQhmP3j8CNv5nOiwtr8AMBbR/yQHMifTLCuEkOMnHZaIieshw7F05U5Y0QUs4hjaUBww+t4JAnn7WiYnU/tt0CCM9fo9J2cVvoaL3E92kmHPWkw735uK3ddf7BwcyJ0hRG3npWYa6HtWDAhe9v/jR6LpnttvFXp2MkAGnoxXOCPsvtVA3xJMHdO7ZtNA+NOd2azwP/fDxPEj8eKNtEfrcnZZpTAxEVSaoqeZqlyeScIJs7P+SHU3OGcL0flk3LKHG7yuhSYvCwRqh5zm5oy6q1ehhIU3QdwfavZEwrMMg06KM4gQYu4LycFCEESJ6ADse8MqTKuIP1nvnLW2lrTPrrVpNOSvnxo7G7wOFUX9c54Qcp8bsElOXFB9+mfncJwphM+PbnU8JLf8GG8a9jGw22TFCIX/BRgp+CD0JNqGN3bZSHy2hRmLbxuvSyZWVQ0OHmlAqiDmqQUJ6ksbk+9Oh6E30Wilf51enkT/rJKMYwc+wf0yKf6SA7kN8MKn938MwmOBLkdmn+QmGvryQrxTCdP5zSIeWL77je/Kn4lzcnw68uruJ5QQgs8oJE9lEUr28cNMbRC7e2YT4ToPGE=
    on:
      repo: atomicateam/atomica
