dist: xenial
sudo: required
language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: deploy
    python: 3.7
    install: skip
    script: skip
    if: NOT type = pull_request
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: romesh
      password: 
        secure: igpBEW8vFJ3RPMfRg5Z83eM9sPmp/OIuw85fvbqpMVHLUF43FMs8p5KW3N1KZxgSODaWic5yevqs83Wkr7brAXcICU+BbNZN3qbqjAmxF+r149qcFh9yEgysCHsw0cyXOb3/zT6aCoV/8VISqNFvGMpDgVMjwIh36+YW43VtjUTp2lmJzRmjZUp/mT42e+nwjkga9+m4UAoHDd8lK9hy9JD1aQUSxpZ3MQrzx6nne03o6weRecEhrtB8BfjOmU1WDmqgLzLL0lD/mW16OWluDzfC34wFf148Mpto9dUQ50iYPeN0E5djJnT47H92HJUkPAyuZNr6eHzkBFFDgd9y9XC/Zp8l6PjcAnoxpPDMuxr3OD9U8gUextfpt9nYL9sEfmxy48Fss5Sb/w8lGD9fL9yPNjt3dMnAMxVEVpRLx24VvUL0dMdW340qPMUP0XlBgvRbfW/hTmDr7Sw2sFZy5G/91KRV+JNR6U4pd21nNI8pobCQnfhVjhBzWKtclpylw2Fe/7x2Vwm4993GFUyfcAm4AHgvZ9auqWclF2xQzGDSdbvOcgLtDEhDpuNuwsuMUoEIphE+8Jc+1sSxWA061Y562BHqczmDv1XNWtW0U9DFpII74e6j42+rtladD9RVnEBC8sCcQPyso6CzB7kxNvHtuHkEqAD9saFGT1y0wYw=
