dist: xenial
sudo: required
language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: deploy
    python: 3.7
    install: skip
    script: skip
    if: NOT type = pull_request
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: romesh
      password:
        secure: k43gr5GYmQyXtI4zSLlFhiWR5CZoAB8V28B4zyruWBE20LrW0wh4aqaPYcyhHUBPJiiAjC29rIvD53j/l1NQdba4KgTM1gKqE8T2KS/WLtIdIBdS1afpUBgyF9POz14hZ+ccpBGtFoGO9r9J/PU36ErnPWHJkxUsknMfnPu2BT2sn2D0+t45/e6dEJCp0c2d1+drJp9t/TjVVr1O6S4mW03ZdZEoXJVMQvh9FC7E5giieVm4bKCoErzwHt637qRAnLnjy6Gkn8b48RTkGLioGY9VGEUlFSBSvL4mpj4uCw5EbG2cTZ5dGdCR2jSF+qWLKyHGng+8lUJWn3dq4uq5g/Vj5PNCIf17NeIBYo2OgwNfmjUEDikQdDvGkYxteyS1fZvGF2B6uf2jI5ccsuR+gyiXUrS5HliXWU0Q3Gex0c/OQHMw/dTLPsppwpNQBYkS0H30XbR1+Cnzbg1Omnd4B3RbjCeD61WbBKCMM49UpB17DB9kml2i/RpZostfSBl7Tqeo/K1x8kOxL0jp3WfaOPhPSrObrOFBY7fKKyHcK/Ro1XIMMV7PdezYw70H555ApvB/KTA2bMJ/SPeNO8s7VWQ/A2OwFB+0UnvuuFdHiP/rSNT85YrdT0Ock+yrPtxRxfdWYa6gz+XXqprn+uW2QZ6jjhfoEGi7Vw0t5+gExk8=
    on:
      repo: atomicateam/atomica
