version: '2'
services:
  app:
    build:
      context: .
      args:
        WHICH: tb
        PORT: '80'
        REDIS_URL: 'redis://redis:6379/7'
    command: python start_server.py
    environment:
      - REDIS_URL=redis://redis:6379/7
    ports:
     - '8080:8080'
     - '8093:8093'
    volumes:
     - .:/code
    depends_on: 
     - redis 

  celery:
    build:
      context: .
      args:
        WHICH: tb
        PORT: '80'
        REDIS_URL: 'redis://redis:6379/7'
    command: celery worker -A atomica_apps.apptasks_tb -l info 
    environment:
      - REDIS_URL=redis://redis:6379/7
  
  redis: 
    image: redis 
    container_name: redis 
    ports: 
      - "6379:6379" 
