version: '2'
services:
  app:
    build:
      context: .
      args:
        WHICH: cascade
        PORT: '80'
        REDIS_URL: 'redis://10.0.0.3:6379/8'
        # REDIS_URL: 'redis://vladh.net:63790/8'
    command: python start_server.py
    environment: 
      - REDIS_URL=redis://10.0.0.3:6379/8 
      # - REDIS_URL=redis://redis:6379/8
    ports:
     - '8080:8080'
     - '8094:8094'
    volumes:
     - .:/code

  celery:
    build:
      context: .
      args:
        WHICH: cascade
        PORT: '80'
        REDIS_URL: 'redis://10.0.0.3:6379/8'
        # REDIS_URL: 'redis://vladh.net:63790/8'
    command: celery worker -A atomica_apps.apptasks_cascade -l info 
    environment: 
      - REDIS_URL=redis://10.0.0.3:6379/8 
      # - REDIS_URL=redis://redis:6379/8
