version: '2'
services:
  app:
    build:
      context: .
      args:
        WHICH: cascade
        PORT: '80'
        REDIS_URL: 'redis://localhost:6379/8'
    command: /etc/init.d/redis-server start && supervisord
    environment:
      - REDIS_URL=redis://localhost:6379/8
    ports:
     - '8080:8080'
     - '8094:8094'
     - '80:80'
    volumes:
     - .:/code
