version: '2'
services:
  app:
    build:
      context: .
      args:
        WHICH: tb
        PORT: '80'
        # REDIS_URL: 'redis://10.0.0.3:6379/7'
        # REDIS_URL: 'redis://vladh.net:63790/7'
        REDIS_URL: 'redis://redis:6379/7'
    command: python run.py
    environment:
      # - REDIS_URL=redis://10.0.0.3:6379/7
      - REDIS_URL=redis://redis:6379/7
    ports:
     - '8080:8080'
     - '8093:8093'
     - '80:80'
    volumes:
     - .:/code
    depends_on:
     - redis

  celery:
    build:
      context: .
      args:
        WHICH: tb
        PORT: '80'
        # REDIS_URL: 'redis://10.0.0.3:6379/7'
        # REDIS_URL: 'redis://vladh.net:63790/7'
        REDIS_URL: 'redis://redis:6379/7'
    command: celery worker -A atomica_apps.apptasks_tb -l info
    environment:
      # - REDIS_URL=redis://10.0.0.3:6379/7
      - REDIS_URL=redis://redis:6379/7

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
