version: '2'
services:
  app:
    build:
      context: .
      args:
        WHICH: tb
        PORT: '80'
        # REDIS_URL: 'redis://10.0.0.19:6379/7' # asia-southeast1-a
        REDIS_URL: 'redis://10.0.0.3:6379/7' # europe-west1-b
    command: supervisord
    environment:
      # - REDIS_URL=redis://10.0.0.19:6379/7 # asia-southeast1-a
      - REDIS_URL=redis://10.0.0.3:6379/7 # europe-west1-b
    ports:
     - '8080:8080'
     - '8093:8093'
     - '80:80'
    volumes:
     - .:/code
