version: '2'
services:
  app:
    build: .
    command: python start_server.py
    # command: bash "source clients/cascade/start_celery.sh && python clients/cascade/start_server.py"
    environment:
      - 'REDIS_URL=redis://redis:6379/8' #this needs to be 7 in TB
    ports:
     - "8080:8080"
     - "8094:8094"
    volumes:
     - .:/code
    depends_on:
     - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
