version: '2'
services:
  app:
    build:
      context: .
      args:
        WHICH: cascade
        PORT: '80'
        # REDIS_URL: 'redis://10.0.0.3:6379/8'
        # REDIS_URL: 'redis://vladh.net:63790/8'
        REDIS_URL: 'redis://redis:6379/8'
    command: python start_server.py
    environment: 
      # - REDIS_URL=redis://10.0.0.3:6379/8 
      - REDIS_URL=redis://redis:6379/8
    ports:
     - '8080:8080'
     - '8094:8094'
     - '80:80'
    volumes:
     - .:/code
    depends_on: 
     - redis 

  celery:
    build:
      context: .
      args:
        WHICH: tb
        PORT: '80'
        REDIS_URL: 'redis://10.0.0.3:6379/8'
        # REDIS_URL: 'redis://vladh.net:63790/8'
    command: celery worker -A atomica_apps.apptasks_tb -l info
    environment: 
      # - REDIS_URL=redis://10.0.0.3:6379/8 
      - REDIS_URL=redis://redis:6379/8

  redis: 
    image: redis 
    container_name: redis 
    ports: 
      - "6379:6379" 
