version: '2'
services:
  app:
    build:
      context: .
      args:
        WHICH: cascade
        PORT: '80'
        REDIS_URL: 'redis://10.0.0.19:6379/8' # asia-southeast1-a
    command: supervisord
    environment:
      - REDIS_URL=redis://10.0.0.19:6379/8
    ports:
     - '8080:8080'
     - '8094:8094'
     - '80:80'
    volumes:
     - .:/code
