version: '2'
services:
  app:
    build: .
    command: python start_server.py
    environment:
      - 'REDIS_URL=redis://database:6379/8'
    ports:
     - "8080:8080"
     - "8094:8094"
    volumes:
     - .:/code
    depends_on:
     - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
