# -*- coding: utf-8 -*-
"""
Optima Core data file.
Sets out a structure to store context-specific values relating to a model, all imported from a databook.
"""

from optimacore.system import applyToAllMethods, logUsage
from optimacore.structure import CoreProjectStructure

@applyToAllMethods(logUsage)
class ProjectData(CoreProjectStructure):
    """ The object that details the transition-network structure of models generated by a project. """
    
    def __init__(self, **kwargs):
        """ Initialize the data container. """
        super(ProjectData, self).__init__(**kwargs)