# -*- coding: utf-8 -*-
"""
Optima Core data file.
Sets out a structure to store context-specific values relating to a model, all imported from a databook.
"""

from optimacore.system import logger, applyToAllMethods, logUsage, accepts, returns, OptimaException

@applyToAllMethods(logUsage)
class ProjectData(object):
    """ The object that details the transition-network structure of models generated by a project. """
    
    def __init__(self):
        """ Initialize the data container. """
        self.name = str()
        self.specs = dict()

    def completeSpecs(self):
        """
        A method for completing specifications that is called at the end of a file import.
        This delay is because some specifications rely on other definitions and values existing in the specs dictionary.
        """
        pass